# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6ac95ab8b6473a34d0ba73e106aaacd838b9e95aafb5ebd708bafa6369dacef76d4416831751c97012db5951f31e3e4c3f545f06076d4e842263c1c02b807d2

test:
  secret_key_base: 594bf73c7b07e4a659bc7e0f7b7de298eae023a123593c56d8eb257709df684bba3387857baea12b6a2d45acf8f6e43148245cfa9df9cf76237f4e6e98ded94e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
